# Services needed for the Joint Cyber program
#
# Current setup includes:
#   - mariadb: The database backend for the server
#   - backend: The application backend, which handles the heavy lifting
#   - frontend: The frontend application, which communicates with the backend
services:
  mariadb:
    image: mariadb
    environment:
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DB}
      MARIADB_ROOT_PASSWORD: ${MYSQL_PASSWORD}
#    ports:
#      - 3306:3306
  backend:
    image: backend
    build:
      context: .
      dockerfile: docker/builds/backend.Dockerfile
    depends_on:
      mariadb:
        condition: service_started
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
