# Services needed for the Joint Cyber program
#
# Current setup includes:
#   - mariadb: The database backend for the server
#   - web: The FastAPI server that hosts the backend and frontend interfaces
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DB}
      MARIADB_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
  web:
    image: web
    restart: always
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      mariadb:
        condition: service_started
    environment:
      MYSQL_HOST: 'mariadb'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
